Fail more gracefully if mandatory option is not correctly set

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -2,6 +2,11 @@
 
 set -euo pipefail
 
+if [[ -z "${BUILDKITE_PLUGIN_JUNIT_ANNOTATE_ARTIFACTS:-}" ]]; then
+  echo "🚨 Missing artifacts configuration for the plugin"
+  exit 1
+fi
+
 PLUGIN_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)/.."
 MAX_SIZE=1024 # in KB
 
